# joy_teleop:
#   ros__parameters:
#     move:
#       type: topic
#       interface_type: geometry_msgs/msg/TwistStamped
#       topic_name: /nebula_controller/cmd_vel

#       deadman_buttons: [5]

#       axis_mappings:
#         twist-linear-x: 
#           axis: 0
#           scale: 3.0
#           offset: 0.0
#         twist-linear-y: 
#           axis: 1
#           scale: 3.0
#           offset: 0.0
#         twist-angular-z:
#           axis: 3
#           scale: 3.0
#           offset: 0.0

# joy_teleop:
#   ros__parameters:
#     move:
#       type: topic
#       interface_type: geometry_msgs/msg/TwistStamped
#       topic_name: /omni_wheel_controller/cmd_vel

#       deadman_buttons: [5]

#       axis_mappings:
#         twist-linear-x: 
#           axis: 0
#           scale: 0.3
#           offset: 0.0
#         twist-linear-y: 
#           axis: 1
#           scale: 0.3
#           offset: 0.0
#         twist-angular-z:
#           axis: 3
#           scale: 0.3
#           offset: 0.0

# joy_teleop:
#   ros__parameters:
#     move:
#       type: topic
#       interface_type: geometry_msgs/msg/Twist
#       # topic_name: /cmd_vel_joy
#       topic_name: /omni_wheel_controller/cmd_vel

#       deadman_buttons: [5]

#       axis_mappings:
#         linear-x: 
#           axis: 1
#           scale: 0.3
#           offset: 0.0
#         linear-y: 
#           axis: 0
#           scale: -0.3
#           offset: 0.0
#         angular-z:
#           axis: 3
#           scale: 0.3
#           offset: 0.0

joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      # topic_name: /omni_wheel_controller/cmd_vel
      topic_name: /cmd_vel_joy

      deadman_buttons: [5]

      axis_mappings:
        twist-linear-x: 
          axis: 0
          scale: -0.3
          offset: 0.0
        twist-linear-y: 
          axis: 1
          scale: 0.3
          offset: 0.0
        twist-angular-z:
          axis: 3
          scale: 0.3
          offset: 0.0