joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: twist_mux/cmd_vel_joy
      deadman_buttons: [5]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.5
          offset: 0
        angular-z:
          axis: 3
          scale: 1.6
          offset: 0
        linear-y:
          axis: 0
          scale: 0.5
          offset: 0